# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\Simulation\ui_files\splashscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(759, 300)
        Frame.setStyleSheet("QFrame{\n"
                            " background-color:rgb(202, 230, 255)\n"
                            "}")
        Frame.setInputMethodHints(QtCore.Qt.ImhNone)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(50, 30, 881, 221))
        self.label.setText("")
        self.label.setPixmap(
            QtGui.QPixmap("src\\Simulation\\ui_files\\../icons/addixo-st gris - fond-transparent (2).png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(280, 230, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_2.setText(_translate("Frame", "EdgeBox Simulation Tool"))
